package com.ak.cryptocrayzcompose.di

data class aa(
    val additional_notices: List<Any>,
    val asset_platform_id: Any,
    val block_time_in_minutes: Int,
    val categories: List<String>,
    val coingecko_rank: Int,
    val coingecko_score: Double,
    val community_score: Double,
    val country_origin: String,
    val developer_score: Double,
    val genesis_date: String,
    val hashing_algorithm: String,
    val id: String,
    val image: İmage,
    val last_updated: String,
    val liquidity_score: Double,
    val market_cap_rank: Int,
    val name: String,
    val preview_listing: Boolean,
    val public_interest_score: Double,
    val public_notice: Any,
    val sentiment_votes_down_percentage: Double,
    val sentiment_votes_up_percentage: Double,
    val status_updates: List<Any>,
    val symbol: String,
    val watchlist_portfolio_users: Int,
    val web_slug: String
)